//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsLogger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnrolledID
    {
        public int EnrollID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public string StudentYear { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual StudentData StudentData { get; set; }
    }
}
