//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsLogger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentData()
        {
            this.Activities = new HashSet<Activity>();
            this.EnrolledIDs = new HashSet<EnrolledID>();
        }
    
        public int ID { get; set; }
        public string StudentName { get; set; }
        public string StudentEmail { get; set; }
        public string StudentID { get; set; }
        public Nullable<System.DateTime> StudentEnrolledDate { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Description { get; set; }
        public Nullable<bool> isRegular { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnrolledID> EnrolledIDs { get; set; }
    }
}
